baseURL = "http://mjladd.github.io"
languageCode = "en-us"
title = "Michael Ladd (mjladd)"
theme = "hugo-xmin"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 2
[[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 4 
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 5 
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 5 
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    footer = "&copy; [Michael Ladd](https://mjladd.com) 2020"
