baseURL = "https://mjladd.com"
locale = "en-us"
title = "Michael Ladd (mjladd)"
theme = "hugo-papermod"
copyright = "&copy; [Michael Ladd](https://mjladd.com) 2020-2026"
enableRobotsTXT = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 4
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 5

[params]
    env = "production"
    description = "Michael Ladd's personal site: blog, reading log, and background."
    mainSections = []
    ShowReadingTime = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = false
    ShowRssButtonInSectionTermList = true
    disableSpecial1stPost = true

[markup]
    [markup.highlight]
        style = "friendly"
        lineNos = true
        lineNumbersInTable = false
        codeFences = true
